enum STATUS {
	NEW, ASSIGNED, OPEN, FIXED, PENDINGRETEST, RETEST, REOPEN, VERIFIED, CLOSED
}

enum PRIORITYBUG {
	HIGH, MEDIUM, LOW
}

enum TYPEBUG {
	RUNTIME, COMPILETIME
}

enum TYPE {
	FINANCE, MAINTAINACE, RESEARCH, RUNTIME
}

enum SEVERITY {
	SEVERE, MILD, LOW
}

enum BUGSTATE {
	WOULDNOTFIXED, CANNOTACCESS, NEEDMOREINFO, FIXED
}
